version: '3.8'
services:
  decvvo:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: decvvo_db
      DATABASE_URL: postgres://postgres:postgres@db:5432/decvvo_db
      REDIS_URL: redis://redis:6379/0
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: decvvo_db
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'